### ISSUE TITLE
Polarr App not named correctly

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#13]
<img width="520" alt="screen shot 2016-07-24 at 6 09 17 pm" src="https://cloud.githubusercontent.com/assets/15273701/17086827/dbb69e08-51c9-11e6-977d-b609a8f2f366.png">
I've purchased Polarr Pro on the Mac App Store, but in Activity Monitor it shows up as Polarr Photo Editor Lite. I don't understand...is the wrong version of the app being distributed on the App Store? At the very least the executable should be renamed because it is very confusing.

**Comment by kpaddie** [comment]
Hi there, we will be looking into this. Thanks!

**Comment by skrimaging** [comment]
I have noticed this as well... I have purchased the full version and all features are unlocked so seems like a mistake in the app plist or something...

**Comment by skrimaging** [comment]
Issue is also present when making app full screen and seeing the name in mission control.

![screen shot 2016-08-01 at 10 33 18 pm](https://cloud.githubusercontent.com/assets/16582747/17315408/406c8cb6-5839-11e6-8b34-78f7f597d7cd.png)

**Comment by kpaddie** [comment]
Hi there,

We're happy to report that this issue has been resolved. Thank you for filing!

Best,

-Polarr team

**Comment by kopaka7** [comment]
Does that mean the Mac update will release today? I don't see it in the App Store yet...
