### ISSUE TITLE
Mac update in the way ?

### ISSUE THREAD

**Issue by bouscram** [Polarrco/polarr_mac_support#14]
HI ! It's been quite a while since there has been a Mac update. When can we expect to see one ? What is in the roadmap is pretty exciting, can't wait to get it...

**Comment by kopaka7** [comment]
I had the same question!

**Comment by kpaddie** [comment]
Yes, we are. We are planning on releasing the new Mac update this week. Stay tuned!

**Comment by skrimaging** [comment]
So glad to know that a Mac update is coming soon!! 

Is there any way to know what to expect from the new update? As Polarr has quickly become my go to Mac app for professional editing, it is hard to not know the roadmap for fixes and features coming to the app.. 

posting a roadmap  (on Facebook, Twitter or maybe on Github)could allow users to know if a feature they really want is coming soon... that way the user will avoid posting feature requests on your Github page if they are already been planned.

**Comment by kpaddie** [comment]
We have a roadmap on our site. It can be found at: https://www.polarr.co/roadmap

**Comment by kopaka7** [comment]
@skrimaging Yeah, the roadmap is above, but I think we skipped over 2.0 because it was due June 30, and the latest version in the App Store is 1.4. My guess is that we will go straight to 2.8.

**Comment by kopaka7** [comment]
@kpaddie Sorry! I had a ticket open for 8-9 days and there was no response so I thought this section had been abandoned in favor of Twitter. I was hoping the update would be out soon because I've been editing a ~2000 picture project and could really use the new features

**Comment by skrimaging** [comment]
@kpaddie So is it right to assume we will be getting brush adjustments this week? If so, I am a happy camper.. 

Also, does the premium feature sync update in 2.8 mean if I purchased the Pro version of Polarr for Mac, It will unlock Pro features for the iOS version aswell?

I also wanted to know if I could sign up for Beta testing future releases of Polarr as I am using you app on my Mac almost exclusively and have much feedback to offer before you release the updates in the wild.

**Comment by kpaddie** [comment]
Hey there,

Yup, brush adjustments will be released this week!

Pro features will not be unlocked across platforms, although, that is something we are working on for future developments.

Once we release the new Polarr for macOS version, please feel free to send any and all feedback to support@polarr.co.

Thanks!

**Comment by skrimaging** [comment]
@kpaddie cool glad to hear this..

As for the feedback, I already send feedback for the current version of app to support email and here on Github.. I wanted to know if there was a beta testing possibility for me so I can post feedback before the app is released... maybe not for version 2.0 as it is imminent but say a version 2.1.

**Comment by kpaddie** [comment]
Hi,

We don't have beta testing needs for Polarr upcoming, but thank you for offering. If you are a iOS user, and you are interested in beta testing, we can add you to a beta testing list for Picky, our new project. Just let us know.

**Comment by skrimaging** [comment]
@kpaddie I am on iOS and interested in beta testing Picky.. I have just sent an email to support@polarr.co regarding this. thanks

**Comment by kpaddie** [comment]
Great! Thanks.

**Comment by skrimaging** [comment]
Has the Mac update been delayed once again?.. I thought it was going to be released last week?

**Comment by bwang29** [comment]
It's under review, and it is repeatedly getting rejected and we're working on it. A reason of being rejected include mentioning "macOS", which is still considered confidential to Apple.

**Comment by skrimaging** [comment]
good to know that the update has been sent from your end.. Hope that it gets approved soon..
Also, thhanks to you and your team for the quick replies! Makes it worth the time to use and give feedback on your app! Keep up the great work and keep us posted when the update is approved. 👍

**Comment by kopaka7** [comment]
The app update just appeared in the Mac App Store 👍 !
