### ISSUE TITLE
[feature_request] Zoom from cursor position.. Not centre of image.

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_mac_support#15]
When I double tap or pinch to zoom 100 %, it always zooms picture from the centre of image.. It would be better if zooming started from the position of the cursor as it does in Apple Photos app.. That way, I can zero in on a specific point of the image instead of zooming to the centre and then trying to pan around to go to the coordinates my cursor already was at.

**Comment by kpaddie** [comment]
Hi, 

Thanks for the suggestion on zooming. I will forward this suggestion along to the engineering team.

**Comment by skrimaging** [comment]
double tap to zoom has been fixed in the 2.0 update.. thanks!... though pinch to zoom still has the prior issue mentioned above. (does not follow cursor position but zooms from centre coordinates of whole image)

For now, I am ok using double tap to zoom as it works as expected but for future updates, please look into implementing the same fix for pinch to zoom as it would provide a smoother workflow for many users.

**Comment by skrimaging** [comment]
Any idea if this issue will see a fix...pinch to zoom still zooms to random part of image instead of where cursor is.
