### ISSUE TITLE
[feature_request] Brush adjustment masks for Mac app

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_mac_support#16]
I love that Gradient and Radial mask tools are available in the MAc app but would love to also have a brush adjustment tool so I can do refined masking to a local area just by brushing using a wacom tablet.. would be great if it handled pressure of stylus aswell.

**Comment by kpaddie** [comment]
Hi there,

Brush adjustment tools are coming in the upcoming version! Stay tuned.
