### ISSUE TITLE
[BUG] EXIF and Metadata is lost when exporting to PNG

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_mac_support#17]
I just noticed that all exif and metadata is lost on export.

My Workflow is as follow:

-import RAW or TIFF file into Polarr for Mac.
-exif info visible  on top while editing.
- once edited, I export to uncompressed png and resulting file has no more exif info or metadata.

Without metadata being preserved, the exported png is pretty much unusable for sharing online or sending in another app for further editing or keeping in archive.

please verify this as it is pretty important to have the metadata.. if this is a limitation of the png format, I hope TIFF export can be added soon.

**Comment by kpaddie** [comment]
Hi there,

Unfortunately, as you mentioned, this is indeed a limitation of the png format. TIFF export is a feature being considered for future development.

Best,

-Polarr team

**Comment by skrimaging** [comment]
Glad to read that TIFF is being considered! Can't wait for that! Thanks
