### ISSUE TITLE
Export Not Working

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#18]
I installed the 2.0 update a few hours ago, but now Export and Batch Export don't work. Both of them lead to nothing happening, but Save and Open seem to be working. I'm stuck with my pictures imported and edited, but unable to export them out. This persists even after closing and opening the app and restarting my Mac completely.

**Comment by skrimaging** [comment]
I just installed the 2.0 update.. export works fine.. tried both batch and single export options.. @kopaka7 were you trying to test the export using the demo image when first launching the app? I tried and that did not export.. but my own images exported fine... really happy with this update so far!

**Comment by kopaka7** [comment]
I have imported a number of images since the new update and can't export any of them...images I edited from the previous version of the app are still in my imported collection and I don't know if that has anything to do with it, but hitting the batch export keyboard shortcut, for instance, does nothing.

**Comment by skrimaging** [comment]
I had no images from the prior version in my app as I had removed them all... try removing those images and testing the export again.. as a last resort, try deleting the app from your Mac and reinstall it from the Mac App Store.

**Comment by bwang29** [comment]
We will review these issues on Monday and do a push next Monday night.

**Comment by kopaka7** [comment]
@skrimaging I had some pending edits to save, so I didn't want to delete the app. I'll use the regular save option for now and then clear imports and reinstall.

**Comment by kopaka7** [comment]
@skrimaging Yeah, deleted the app, restarted, and opened completely new photos and I still can't export anything.

**Comment by skrimaging** [comment]
I have finally reproduced your issue @kopaka7 

If I am right, you click export using the file menu in menu bar of osx and nothing happens.

try using the little square sharing icon in the app UI..

then click on  "format,resize, watermark option" and it should work...

![screen shot 2016-08-15 at 6 52 41 pm](https://cloud.githubusercontent.com/assets/16582747/17685559/2304ebdc-6333-11e6-8481-adebbe468254.png)

@bwang29 issue seems to be in the file menu items not responding.

![screen shot 2016-08-15 at 6 53 01 pm](https://cloud.githubusercontent.com/assets/16582747/17685595/6f53a3b6-6333-11e6-9ced-076a69f9d1ce.png)

**Comment by bwang29** [comment]
Yep, it's already fixed and a new update is submitted, together with the new vibrance slider.

**Comment by kopaka7** [comment]
@skrimaging I think you nailed it. I didn't even know there was another way to get to Export. I tried updating again and accessing the way you noted and it seemed to work. 
@bwang29 Great! Looking forward to the update!

**Comment by kopaka7** [comment]
Yup, it's working with the update. Just a quick follow-up: What's the difference between Save and Export? Does Save just default to the same settings as Export?

**Comment by skrimaging** [comment]
@kopaka7 save defaults to quicly exporting the image to a jpg.. export gives you moreoptions like watermark and choice of Tiff export format
