### ISSUE TITLE
Polarr does not start if proxy is used

### ISSUE THREAD

**Issue by prokrastinix** [Polarrco/polarr_mac_support#2]
As soon as I define an HTTP/HTTPS proxy for the Mac (squid) in the Network Settings, Polarr refuses to start with the progress bar hanging at 80% endlessly. The same holds true if the proxy is defined using Proxy Auto Configuration (i.e. a proxy.pac on a web server).

According to the proxy access log, there is not even a request approaching the proxy. If I remove the proxy settings, everything works smoothly. However, changing the proxy settings every time prior to starting Polarr is a wee bit inconvenient. 

![screen shot 2016-05-24 at 10 14 03](https://cloud.githubusercontent.com/assets/11961911/15497906/453a2c26-219d-11e6-9fd5-eb2c0a2689a7.png)

**Comment by bwang29** [comment]
Thanks for the info, we will see if we can fix it in the upcoming update end of this month (v4.0 release). Sorry for the delay in response as we've been hacking v4 over the past few months now.

**Comment by mrscourtneysmith** [comment]
Hi, I am trying to use this app as well and I am having the same issues. I am very new to programming so I am not sure how to change the proxy settings. Can someone help a girl out?
