### ISSUE TITLE
[feature_request] Straighten in history

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#20]
Can we get the straighten degree amount in the history as it was in the 1.4 update? Cropping appears in history but straighten seems to no longer be there. I notice that combining straightening with adjustments doesn't work, because undoing an adjustment will take out the straightening as well.

**Comment by seanpkent** [comment]
@kopaka7 Thanks! This is definitely a bug. This has been fixed and will be in an upcoming release soon.
