### ISSUE TITLE
Warped display while straightening

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#21]
<img width="866" alt="screen shot 2016-08-16 at 4 01 47 pm" src="https://cloud.githubusercontent.com/assets/15273701/17713849/0913728c-63cb-11e6-9de9-e4aa3d1ea49b.png">
I noticed that when you straighten an image and then hit 'A' to move to the adjustments tab, unless you clicked on the image first, the image will appear warped, as seen in the screenshot below. This doesn't affect the image output, just what is displayed on screen.
<img width="861" alt="screen shot 2016-08-16 at 4 02 05 pm" src="https://cloud.githubusercontent.com/assets/15273701/17713848/090191ac-63cb-11e6-8981-5bb5e0306e4f.png">

**Comment by seanpkent** [comment]
@kopaka7 Thanks for submitting this issue! This has been fixed and will be released soon.
