### ISSUE TITLE
"zero" position of the sliders not visible

### ISSUE THREAD

**Issue by bouscram** [Polarrco/polarr_mac_support#24]
Some of the sliders have only a positive value (so the "zero" is on the left), while some can have positives and negatives values (so the "zero" is in the middle). There should be a way to see it (like a line in the center for the latter). 
I don't remember well, but I think they were more visible in versions 1.x

**Comment by skrimaging** [comment]
+1 I have noticed this aswell for many sliders.. I tend to think that the 0 is in the middle only to find out by accident that some have the 0 in the left...

**Comment by kpaddie** [comment]
Hi,

Thank you for your feedback on the slider design. We will consider this as a possibility for future versions of the app.

Best,

-Polarr team
