### ISSUE TITLE
"Open photo in Polarr" No longer working smoothly

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#26]
Prior to the 2.0 update, I was able to open photos from Finder directly into Polarr without the app being previously open by right-clicking and selecting Polarr in the Open With option. Now when I do this, the app will open, but the photo I am trying to edit does not always open up. Before it worked 100% of the time.

**Comment by kpaddie** [comment]
Hi Kopaka,

Thanks for alerting us to this issue. What is your device and OS?

**Comment by kopaka7** [comment]
The device is a MacBook Pro Retina running El Capitan.
