### ISSUE TITLE
disappearance of the function "mixing the original pic and the actual pic" ?!?

### ISSUE THREAD

**Issue by tayo3** [Polarrco/polarr_mac_support#27]
Hello, I search the function which permit to mix the original pic and the pic we are editing but impossible to find it. Have you deleted it ?
If yes what a pity, it was a really cool function !

BR

PS : the app is really cool for a free app, thank's !

**Comment by kpaddie** [comment]
Hi Tayo,

In the latest version, we were forced to remove some of the least-used features, and this was one. You can still replicate the effect of "Mix with Original" by editing the photo, saving the edits as a custom filter, then adjusting the strength of the filter to your liking.

Thanks!

-Polarr team

**Comment by tayo3** [comment]
Ok thank's for the tip :)
