### ISSUE TITLE
Image flipping when toggling comparison

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#28]
When I press the spacebar to view the original version of an image, it immediately becomes unclear and also flips 180 degrees. This remains on the screen until I press the spacebar again and then it goes back to normal. I have a screenshot of the phenomenon. **This also leads to image edits being completely unviewable unless the app is restarted, I just noticed**
<img width="854" alt="screen shot 2016-08-28 at 11 42 21 pm" src="https://cloud.githubusercontent.com/assets/15273701/18040210/41eb595a-6d79-11e6-8888-ac014c2edc7d.png">
For reference, this is the actual picture
<img width="843" alt="screen shot 2016-08-28 at 11 44 34 pm" src="https://cloud.githubusercontent.com/assets/15273701/18040223/6ca505c4-6d79-11e6-975e-723e21158275.png">

**Comment by kpaddie** [comment]
Hi,

This is a bug that we have not yet found the solution for, but are looking into. For now, as you noted, the image will return to normal with a second spacebar tap.

Best,

-Polarr team
