### ISSUE TITLE
Changelog for Polarr 2.1

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#30]
Can we please get a quick overview of what bugs were fixed with 2.1.0? The Mac App Store details appeared to largely resemble the release notes of the 2.0 version.

**Comment by bwang29** [comment]
2.1 is adding Yosemite support and adding guide panel, a lot of the issues in here will be addressed in 2.2.

**Comment by kopaka7** [comment]
Okay, thanks, I wanted to know which bug fixes to look out for
