### ISSUE TITLE
Copy the effects of a pic

### ISSUE THREAD

**Issue by tayo3** [Polarrco/polarr_mac_support#35]
Hello, just a little question : Is it possible to copy all the effects of a pic and paste them to another ? (in order to have all the same pics with the same tonality in the burst mode of a camera by example)

Thanks (and sorry if it was already asked, I didn't see it)

**Comment by kpaddie** [comment]
Hi there,

Currently, we do not have this option. However, we will be looking into it for future versions.

Best,

-Polarr team
