### ISSUE TITLE
Polarr listening port (TCP)

### ISSUE THREAD

**Issue by pedrohagel** [Polarrco/polarr_mac_support#39]
Hi,

Few days ago I purchased Polarr Photo Editor (Mac App Store).
I noticed it is constantly listening to a given TCP port.
As an example, lsof -i would return something like "Polarr TCP *:51407 (LISTEN)".

Can you please clarify the reason for this listening service?
Also, what would be the expected behavior if I were to block it (firewall)?

Thank you in advance.

**Comment by bwang29** [comment]
This port is properly sandboxed after Apple's investigation. Closing issue.
