### ISSUE TITLE
Color difference when saving a raw edit to JPEG.

### ISSUE THREAD

**Issue by ph0real** [Polarrco/polarr_mac_support#4]
Hi,

When I edit RAW files with the photos extension and export a JPEG, there's a significant color difference between the saved file shown in the extension view and the saved exported jpeg showed in photos.

This is consistent with every edit i make. It makes editing really troublesome because the colors don't match what i've configured with the extension. The output file always shows much more saturated colors.

Steps I take:
Select photo in photos app. Click edit. Click the polarr app under Extensions. 
Make edits in Polarr. Click save changes. Back in photos the photo shows more saturated.

Any idea whats going on here?

Sidenote: once i open the saturated JPEG in polarr again, the colours turn into the desired amount of saturation. There seems to be a difference in color profiles between Polar and the photos app.

![schermafbeelding 2016-05-27 om 17 31 43](https://cloud.githubusercontent.com/assets/19611775/15613009/94d93f1a-2431-11e6-8a81-4c1f2d116c60.png)
![schermafbeelding 2016-05-27 om 17 32 23](https://cloud.githubusercontent.com/assets/19611775/15613014/99dc831e-2431-11e6-8149-b6bac6729c65.png)

**Comment by bwang29** [comment]
Thanks for the info, we will see if we can fix it in the upcoming update end of this month (v4.0 release). Sorry for the delay in response as we've been hacking v4 over the past few months now.

**Comment by chizzler** [comment]
I'm a new polarr user on OSX and while the app is great, i'm experiencing the exact issue described above and its super frustrating.

**Comment by emilio888** [comment]
Hi I have the same issue with Polarr on Mac OS 10.10.5 Yosemite. This is very frustrating because I want to buy your full app but i'm not sure anymore. Please fix.

thanks
