### ISSUE TITLE
How to import a custom filter that created by old version.

### ISSUE THREAD

**Issue by AquiTCD** [Polarrco/polarr_mac_support#40]
I have made some custom filters before, like file.polarr
but version 3.1.0 does not recognise the extension of ".polarr" and
it's impossible to import them.
any other way to import?

**Comment by kpaddie** [comment]
Hi there,

Do you have the QR code for the older custom filters? If so, you can import them as a photo, or scan them to import in the Filters menu.

Very best,

-Polarr team

**Comment by AquiTCD** [comment]
Hi
of course  I know the importing way by QR code.
but I don't have any code, instead of .polarr files.
then how I can?
