### ISSUE TITLE
[Bug] Holding down the "B" key to compare before/after makes a noise in system

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_mac_support#45]
If you hold down the "B" keyboard shortcut to compare the before /after view, it will make an annoying clicking sound coming from speakers on my Mac for the amount of time I keep the B key held... this happens on all the Mac computers I have tried with Polarr.

**Comment by bwang29** [comment]
This is some weird GPU interference, and we don't know what cause it. Can't reproduce.

**Comment by skrimaging** [comment]
@bwang29 I am able to reproduce issue on all my Macs and also other macs. The sound is not coming from internal component or chip.

This sound is the macOS letting user know that a key is being held. Happens in other apps like text editors for example.

I think code change in Polarr needs to be in place so the holding of key is ignored by macOS in app.

**Comment by seanpkent** [comment]
@skrimaging You are correct. This is not any kind of interference. I fixed this in a previous release, so I'm not sure why you are still hearing the sound. Are you using the latest version?

**Comment by skrimaging** [comment]
@seanpkent Sorry, I was using version 3.3.0.. just saw the update in Mac App Store for 3.4.1... installing now..

**Comment by seanpkent** [comment]
@skrimaging No prob. Glad to know it's not an issue anymore!
