### ISSUE TITLE
Cross Platform?

### ISSUE THREAD

**Issue by KoertD** [Polarrco/polarr_mac_support#46]
I just heard a review for Polarr photo editor and they were touting that it worked on a bunch of different platforms. I already have Adobe Creative Cloud and was looking primarily for an editor that would work on my iPhone and iPad Pro. But when I paid for and downloaded the app from my iMac, it looks like I need separate versions for each platform.

Is that correct? If so, I'd rather have the iPhone version than the iMac version.

Thanks.

**Comment by kpaddie** [comment]
Hi Koert,

We have apps available for nearly all platforms: iOS, Android, Windows, Web, Mac, Chrome, Linux, and BlackBerry.

However, we are not a cloud-based service, and macOS and iOS versions must be sold separately. We are happy to send you an unlock code for iOS if you email support@polarr.co

Best,

-Polarr team
