### ISSUE TITLE
Exporting with EXIF rotation

### ISSUE THREAD

**Issue by RockyMM** [Polarrco/polarr_mac_support#5]
I noticed that images that are in portrait orientation when exported from Polarr Lite lose their orientation and become landscape oriented.

I will try later with Polarr Pro (big props for the discount) to try to confirm.

**Comment by bwang29** [comment]
Thanks for the info, we will see if we can fix it in the upcoming update end of this month (v4.0 release). Sorry for the delay in response as we've been hacking v4 over the past few months now.
