### ISSUE TITLE
[Bug] Polarr stays on black screen on macOS Sierra 10.12.4 Public Beta 1

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_mac_support#55]
I recently installed macOS Sierra 10.12.4 Beta 1 on a separate test partition on my Mac and am testing a few of my apps to see if any give issues... I noticed Polarr is not working in this Beta.. using latest Polarr release for Mac.. 

I open the app and it just shows a black screen and nothing else.. tried online and offline but same issue.

Don't know if anyone else is having this issue on the latest Sierra Beta.

@seanpkent @bwang29

**Comment by coreyallen** [comment]
I'm experiencing this as well

**Comment by bonka** [comment]
This is happening for me as well. Getting Tired of Polarr not working anywhere. I paid for both versions, and they don't work [anywhere](https://github.com/Polarrco/polarr_ios_android_support/issues/21)

![black polarr](https://cloud.githubusercontent.com/assets/1240278/22802326/aa5c19e8-ef10-11e6-911d-a4031056ced0.png)

**Comment by skrimaging** [comment]
running macOS 10.12.4 beta 7 and issue has been fixed... I can now open Polarr and use it.
