### ISSUE TITLE
Next update

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#61]
I know an update has been mentioned in response to some of the recent issues, but is there a timeline for when it is releasing? I think the last update was back in February. I've had to fill up my workspace because I'm holding off on exporting anything until the EXIF bug patch comes out.

**Comment by skrimaging** [comment]
Same here, Polarr has issues handling exposure adjustments (see https://github.com/Polarrco/polarr_mac_support/issues/54) and has not seen a fix for a while.

I am glancing in the Mac App Store'S update tab to see if an update is available for Polarr every week.

@bwang29 Can anyone from the Polarr team give us an indication as to what fixes are being worked on so we can at least know when and what to expect?.. also, if any Beta testing is needed, I offer my help.. I really want to use Polarr as it provides me with iOS and Mac editing options but for now most of my editing is being backlogged or delegated to other apps.

**Comment by seanpkent** [comment]
@kopaka7 @skrimaging The updated lite version is now live on the Mac app store. The pro version is currently in review, so it should be live within a day or so. We know this update has been overdue, but we have several big changes to the design. There is a new filmstrip layout and a redesigned export menu. I've completely rewritten the brush mask tool and most of the code has been refactored for performance and stability so you should notice a difference rendering speed. 
@skrimaging I'm still working on better image decoding (higher bit-depth) and color profile support which should fix the exposure issues.

**Comment by skrimaging** [comment]
@seanpkent thanks for the reply! looking forward to testing the Pro version update when released.

**Comment by kopaka7** [comment]
@seanpkent Glad to hear the update is coming soon.

**Comment by kopaka7** [comment]
Just got the new update! Very exciting!
