### ISSUE TITLE
Batch Export

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_support#63]
I tried batch exporting all my photos in the filmstrip. I clicked to apply current adjustments and saved, but I noticed the pictures looked different from how they did in Polarr. I attached a screenshot comparison. The one at the left was batch exported, at the right was single-exported. No edits were changed between the two. If I select neither current adjustment nor auto, I get a picture that looks like Polarr. However, if I select auto, a third type is produced. I want to know what the difference is here, because "current adjustments" sounds like it should export as seen in Polarr, but doesn't.
<img width="387" alt="screen shot 2017-04-17 at 12 09 29 pm" src="https://cloud.githubusercontent.com/assets/15273701/25094862/fdfcc324-2366-11e7-956d-64918b6906e1.png">
This second screen shows the changes in the 3 versions.
<img width="580" alt="screen shot 2017-04-17 at 12 17 27 pm" src="https://cloud.githubusercontent.com/assets/15273701/25095041/e342f1ba-2367-11e7-92b4-568ebc78a651.png">

**Comment by seanpkent** [comment]
@kopaka7 selecting "Current adjustments" will apply the adjustments of the currently opened photo to all photos. If you loaded a different photo before exporting this one, then it would have the adjustments of the opened photo if you choose "Current adjustments" I hope that's clear.

**Comment by kopaka7** [comment]
Okay, let me see if that fixes it. Is there documentation for all this somewhere? I can only find a guide to the different editing tools.

**Comment by kopaka7** [comment]
@seanpkent When I'm exporting without checking any boxes, nothing seems to happen even after waiting several minutes.

**Comment by kopaka7** [comment]
With the latest update, batch export does seem to be working. I was able to export all 150+ photos I had in workspace, where before nothing happened.
