### ISSUE TITLE
Photo does not open

### ISSUE THREAD

**Issue by bjsp21** [Polarrco/polarr_mac_support#64]
Since I updated to version 3.7.0 on my iMac (Sierra OS), I cannot open new photo anymore. I see 'Opening photo' on the screen but it does stuck there. 
(I tried both "File -> Open -> Select a photo" and "Right click on photo -> Open with -> Polarr Photo Editor 3.7.0", but same result). 

![screenshot](https://cloud.githubusercontent.com/assets/27799646/25215600/9123eb8a-256c-11e7-9a23-c36d25443dfd.jpeg)

**Comment by yan7109** [comment]
@bjsp21 what version of sierra are you running with? Also, could you attach a photo that does not load for you? thanks!

**Comment by bjsp21** [comment]
It's Sierra version 10.12.4. This page does not allow to attach sample photos those are bigger than 10MB. I will send them in email. (sound weird but I am having problem with lots of portrait photos).

**Comment by bjsp21** [comment]
I verified it and the issue has been fixed in Version 3.8.0. Thanks!!

**Comment by yan7109** [comment]
awesome, thanks!
