### ISSUE TITLE
Posterization and banding in Fuji RAW files

### ISSUE THREAD

**Issue by harunkucuk** [Polarrco/polarr_mac_support#7]
Hi,

I find that Polarr produces posterization and banding when working with Fuji RAW files. Is this an issue with Polarr or with OSX RAW support? I moved from DxO recently, because it doesn't support Fuji files. Never had this problem. Thanks. 
![dscf0213](https://cloud.githubusercontent.com/assets/6297217/16006634/2422fcb2-313c-11e6-9635-58892e6fbf28.jpeg)
![dscf0335](https://cloud.githubusercontent.com/assets/6297217/16006653/31cced00-313c-11e6-8e92-6fed5bc89064.jpeg)

**Comment by bwang29** [comment]
Polarr uses Mac's Camera RAW utility to decode RAW. This usually means the format has not been fully supported by Mac OSX's built in RAW decoder yet and a future update might fix it.

**Comment by bwang29** [comment]
By the way, there is no "banding" effect on the uploaded image?
