### ISSUE TITLE
[bug]Can not import any RAW file.

### ISSUE THREAD

**Issue by KOSKERS** [Polarrco/polarr_mac_support#8]
When i try to import the NEF&CR2 file. the application say can not load this picture.

Linux version

**Comment by bwang29** [comment]
Linux version is unfortunately no longer supported. Our desktop app focus will be Windows and Mac moving forward.

**Comment by dogeatery** [comment]
I was just about to pay for hte pro version but I'm reading htat Linux will no longer be supported. What? There is nothing like this on Linux :(
