### ISSUE TITLE
Zoom lost when changing values in a radial mask, also cannot pan

### ISSUE THREAD

**Issue by iandol** [Polarrco/polarr_mac_support#9]
The radial mask workflow is really broken when zoomed in to a picture. Zoom in (pinch gesture or click 1:1 button):

1) Every time you make a change to the filter, Polarr zooms back out to show whole picture. Incredibly frustrating. Often you need to be zoomed in to really see what a radial mask is doing.
2) There seems no clear way to pan when you are editing a radial filter, so if you want to zoom in then pan to the part of the image (because after zooming you cannot see the part you need) you cannot do so. I tried [space] ⌘ ⌥ ⇧ and mouse but no luck.

**Comment by skrimaging** [comment]
same issue is present when in Gradient Mask mode as well. keeps zooming out to fit view and no panning option..

**Comment by skrimaging** [comment]
fixed in version 2.0.... thanks
